# Generated by Django 4.2 on 2023-05-23 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_time_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 23, 19, 27, 54, 574722, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('p', 'Post'), ('p', 'Post'), ('a', 'Answer')], max_length=1),
        ),
    ]
