# Generated by Django 4.2 on 2023-05-24 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askme', '0002_post_data_time_creation_alter_like_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like2Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(-1, 'Minus'), (0, 'Neutral'), (1, 'Plus')])),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Like2Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(-1, 'Minus'), (0, 'Neutral'), (1, 'Plus')])),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.post')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='static/img/default_avatar.jpg', upload_to='static/img/ava')),
                ('like2answer', models.ManyToManyField(to='askme.like2answer')),
                ('like2post', models.ManyToManyField(to='askme.like2post')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askme.myuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askme.myuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
